# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [5]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [6]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

Saving peserta_pelatihan_umkm_2025.csv to peserta_pelatihan_umkm_2025.csv
(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [8]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)

# a. Cetak daftar nama kolom beserta tipe datanya
print(df.info())

# b. Cetak jumlah baris dan kolom
print(f"{df.shape[0]} baris x {df.shape[1]} kolom")
# Expected: 620 baris x 28 kolom

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_peserta                   620 non-null    object
 1   nama_lengkap                 620 non-null    object
 2   nik_dummy                    620 non-null    int64
 3   no_hp                        611 non-null    float64
 4   email                        620 non-null    object
 5   alamat_jalan                 620 non-null    object
 6   kelurahan                    620 non-null    object
 7   kecamatan                    620 non-null    object
 8   kota                         620 non-null    object
 9   tanggal_lahir                620 non-null    object
 10  jenis_kelamin                620 non-null    object
 11  pendidikan_terakhir          620 non-null    object
 12  status_disabilitas           620 non-null    object
 13  jumlah_anak                  620 non-null    int64
 14  penghasilan_pribadi_bulanan  620 non-null    int64
 15  nama_usaha                   620 non-null    object
 16  kategori_usaha               620 non-null    object
 17  produk_utama                 620 non-null    object
 18  lama_usaha_tahun             620 non-null    float64
 19  jumlah_karyawan              620 non-null    int64
 20  omzet_usaha_bulanan          620 non-null    int64
 21  pernah_ikut_pelatihan        620 non-null    object
 22  kanal_pendaftaran            620 non-null    object
 23  tanggal_daftar               620 non-null    object
 24  kehadiran_persen             620 non-null    int64
 25  skor_prates                  620 non-null    int64
 26  skor_pascates                586 non-null    float64
 27  tingkat_kepuasan             602 non-null    float64
dtypes: float64(4), int64(7), object(17)
memory usage: 135.8+ KB
None
620 baris x 28 kolom

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _(tulis di sini)_ — Kolom: _(tulis di sini)_
2. Perbaikan: _(tulis di sini)_ — Kolom: _(tulis di sini)_
3. Mengapa uji kolom gagal: _(tulis di sini)_

In [9]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

# Mencari semua kolom yang mengandung kata 'omzet' pada dataframe 'df'
omzet_columns = [col for col in df.columns if "omzet" in col.lower()]
print(f"Kolom yang memuat kata 'omzet': {omzet_columns}")

# Pembuktian logika
if len(omzet_columns) == 1:
    print(
        "Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan."
    )
else:
    print(
        f"Ditemukan {len(omzet_columns)} kolom yang memuat kata 'omzet': {omzet_columns}"
    )

Kolom yang memuat kata 'omzet': ['omzet_usaha_bulanan']
Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan.

In [10]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

# Mencari semua kolom yang mengandung kata 'omzet' pada dataframe 'df'
omzet_columns = [col for col in df.columns if "omzet" in col.lower()]
print(f"Kolom yang memuat kata 'omzet': {omzet_columns}")

# Pembuktian logika
if len(omzet_columns) == 1:
    print(
        "Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan."
    )
else:
    print(
        f"Ditemukan {len(omzet_columns)} kolom yang memuat kata 'omzet': {omzet_columns}"
    )

Kolom yang memuat kata 'omzet': ['omzet_usaha_bulanan']
Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan.

In [11]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

# Mencari semua kolom yang mengandung kata 'omzet' pada dataframe 'df'
omzet_columns = [col for col in df.columns if "omzet" in col.lower()]
print(f"Kolom yang memuat kata 'omzet': {omzet_columns}")

# Pembuktian logika
if len(omzet_columns) == 1:
    print(
        "Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan."
    )
else:
    print(
        f"Ditemukan {len(omzet_columns)} kolom yang memuat kata 'omzet': {omzet_columns}"
    )

Kolom yang memuat kata 'omzet': ['omzet_usaha_bulanan']
Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan.

In [12]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

# Mencari semua kolom yang mengandung kata 'omzet' pada dataframe 'df'
omzet_columns = [col for col in df.columns if "omzet" in col.lower()]
print(f"Kolom yang memuat kata 'omzet': {omzet_columns}")

# Pembuktian logika
if len(omzet_columns) == 1:
    print(
        "Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan."
    )
else:
    print(
        f"Ditemukan {len(omzet_columns)} kolom yang memuat kata 'omzet': {omzet_columns}"
    )

Kolom yang memuat kata 'omzet': ['omzet_usaha_bulanan']
Terbukti: Hanya ada 1 kolom omzet (omzet saat mendaftar). Tidak ada kolom omzet sesudah pelatihan.

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | | |
| `pendidikan_terakhir` | | |
| `skor_prates` | | |
| `omzet_usaha_bulanan` | | |
| `jumlah_karyawan` | | |
| `tingkat_kepuasan` | | |
| `tanggal_daftar` | | |
| `kecamatan` | | |

In [13]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
# c. Cetak median jenjang pendidikan lewat .cat.codes
# Expected: median = SMA/SMK

# Define the order for pendidikan_terakhir
pendidikan_order = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']

# Convert the column to an ordered categorical type
df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'], categories=pendidikan_order, ordered=True
)

# Display value_counts() sorted by jenjang
print("Value counts for 'pendidikan_terakhir' (ordered by jenjang):")
print(df['pendidikan_terakhir'].value_counts().sort_index())

# Calculate and print the median jenjang pendidikan
median_code = df['pendidikan_terakhir'].cat.codes.median()
median_jenjang = pendidikan_order[int(median_code)]
print(f"\nMedian jenjang pendidikan: {median_jenjang}")

Value counts for 'pendidikan_terakhir' (ordered by jenjang):
pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64

Median jenjang pendidikan: SMA/SMK

In [14]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
# Expected: rentang pendaftaran berada di tahun 2025

df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

min_tanggal_daftar = df['tanggal_daftar'].min()
max_tanggal_daftar = df['tanggal_daftar'].max()

print(f"Tanggal pendaftaran paling awal: {min_tanggal_daftar.strftime('%Y-%m-%d')}")
print(f"Tanggal pendaftaran paling akhir: {max_tanggal_daftar.strftime('%Y-%m-%d')}")

Tanggal pendaftaran paling awal: 2025-02-01
Tanggal pendaftaran paling akhir: 2025-05-31

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [15]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom

kolom_data = []
for col in df.columns:
    kolom_data.append({
        'nama_kolom': col,
        'tipe_data': df[col].dtype,
        'nilai_unik': df[col].nunique(),
        'nilai_kosong': df[col].isnull().sum(),
        'contoh_nilai': df[col].dropna().iloc[0] if not df[col].dropna().empty else None
    })

kamus = pd.DataFrame(kolom_data)

# Add the four empty columns
kamus['deskripsi'] = ''
kamus['skala_pengukuran'] = ''
kamus['kategori_data_pribadi'] = ''
kamus['tindakan_penanganan'] = ''


display(kamus)
print(f"Shape of kamus: {kamus.shape[0]} baris x {kamus.shape[1]} kolom")

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,,,,
1,nama_lengkap,object,450,0,Ratna Hidayat,,,,
2,nik_dummy,int64,620,0,99991405899249,,,,
3,no_hp,float64,611,9,80004260813.0,,,,
4,email,object,450,0,ratna.hidayat@contoh.example,,,,
5,alamat_jalan,object,620,0,Jl. Cempaka No. 106 RT 02/RW 10,,,,
6,kelurahan,object,26,0,Sukatani,,,,
7,kecamatan,object,19,0,Tapos,,,,
8,kota,object,1,0,Depok,,,,
9,tanggal_lahir,datetime64[ns],598,0,1989-05-14 00:00:00,,,,
10,jenis_kelamin,object,2,0,P,,,,
11,pendidikan_terakhir,category,6,0,SMP,,,,
12,status_disabilitas,object,2,0,Tidak,,,,
13,jumlah_anak,int64,5,0,3,,,,
14,penghasilan_pribadi_bulanan,int64,110,0,500000,,,,
15,nama_usaha,object,185,0,CV Mandiri Jaya,,,,
16,kategori_usaha,object,5,0,Kuliner,,,,
17,produk_utama,object,19,0,Roti dan kue,,,,
18,lama_usaha_tahun,float64,119,0,12.8,,,,
19,jumlah_karyawan,int64,11,0,4,,,,
20,omzet_usaha_bulanan,int64,293,0,2950000,,,,
21,pernah_ikut_pelatihan,object,2,0,Tidak,,,,
22,kanal_pendaftaran,object,4,0,Datang langsung,,,,
23,tanggal_daftar,datetime64[ns],120,0,2025-04-04 00:00:00,,,,
24,kehadiran_persen,int64,46,0,75,,,,
25,skor_prates,int64,64,0,52,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

Shape of kamus: 28 baris x 9 kolom

In [16]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
# Expected: tepat 3 kolom yang punya nilai kosong

kolom_kosong = kamus[kamus['nilai_kosong'] > 0]
display(kolom_kosong)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | | | |
| `kehadiran_persen` | | | |
| `skor_pascates` | | | |
| `kanal_pendaftaran` | | | |
| `jumlah_anak` | | | |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [17]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Buat dictionary bernama PENANDAAN berisi pasangan:
#     'nama_kolom': ('kategori', 'tindakan')
# Tindakan yang tersedia: 'hapus', 'hash', 'generalisasi', 'pertahankan'
# Kolom yang tidak Anda daftarkan dianggap 'bukan data pribadi' + 'pertahankan'.
#
# Lalu bangun DataFrame 'tanda' dengan kolom: nama_kolom, kategori, tindakan
# dan cetak jumlah kolom per kategori.
# Expected: pengenal langsung >= 5 kolom; data spesifik >= 3 kolom

PENANDAAN = {
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hash'),
    'no_hp': ('pengenal langsung', 'hash'),
    'email': ('pengenal langsung', 'hash'),
    'alamat_jalan': ('quasi-identifier', 'hapus'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'tanggal_lahir': ('data spesifik', 'generalisasi'),
    'status_disabilitas': ('data spesifik', 'pertahankan'),
    'jumlah_anak': ('data spesifik', 'pertahankan'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'pertahankan'),
    'omzet_usaha_bulanan': ('data spesifik', 'pertahankan'),
    'nama_usaha': ('quasi-identifier', 'pertahankan') # Often debated, but keeping for now per prompt hint
}

tanda_list = []
for col in df.columns:
    kategori, tindakan = PENANDAAN.get(col, ('bukan data pribadi', 'pertahankan'))
    tanda_list.append({
        'nama_kolom': col,
        'kategori': kategori,
        'tindakan': tindakan
    })

tanda = pd.DataFrame(tanda_list)

print("Jumlah kolom per kategori:")
print(tanda['kategori'].value_counts())
display(tanda)

Jumlah kolom per kategori:
kategori
bukan data pribadi    14
pengenal langsung      5
data spesifik          5
quasi-identifier       4
Name: count, dtype: int64

                     nama_kolom            kategori      tindakan
0                    id_peserta   pengenal langsung          hash
1                  nama_lengkap   pengenal langsung         hapus
2                     nik_dummy   pengenal langsung          hash
3                         no_hp   pengenal langsung          hash
4                         email   pengenal langsung          hash
5                  alamat_jalan    quasi-identifier         hapus
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier  generalisasi
8                          kota  bukan data pribadi   pertahankan
9                 tanggal_lahir       data spesifik  generalisasi
10                jenis_kelamin  bukan data pribadi   pertahankan
11          pendidikan_terakhir  bukan data pribadi   pertahankan
12           status_disabilitas       data spesifik   pertahankan
13                  jumlah_anak       data spesifik   pertahankan
14  penghasilan_pribadi_bulanan       data spesifik   pertahankan
15                   nama_usaha    quasi-identifier   pertahankan
16               kategori_usaha  bukan data pribadi   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun  bukan data pribadi   pertahankan
19              jumlah_karyawan  bukan data pribadi   pertahankan
20          omzet_usaha_bulanan       data spesifik   pertahankan
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran  bukan data pribadi   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen  bukan data pribadi   pertahankan
25                  skor_prates  bukan data pribadi   pertahankan
26                skor_pascates  bukan data pribadi   pertahankan
27             tingkat_kepuasan  bukan data pribadi   pertahankan

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | | | |
| `omzet_usaha_bulanan` | | | |
| `id_peserta` | | | |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [18]:
columns_to_drop = tanda[tanda['tindakan'] == 'hapus']['nama_kolom'].tolist()

aman = df.drop(columns=columns_to_drop)

num_dropped = len(columns_to_drop)
num_remaining = aman.shape[1]

print(f"Jumlah kolom yang dibuang: {num_dropped}")
print(f"Jumlah kolom yang tersisa: {num_remaining}")

Jumlah kolom yang dibuang: 2
Jumlah kolom yang tersisa: 26

In [28]:
GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan
    # Convert all values to string before hashing
    hashed_value = hashlib.sha256(str(garam).encode() + str(nilai).encode()).hexdigest()
    return hashed_value[:12]

columns_to_hash = tanda[tanda['tindakan'] == 'hash']['nama_kolom'].tolist()

for col in columns_to_hash:
    aman[col] = aman[col].apply(lambda x: samarkan(x, GARAM))

print(f"Kolom yang di-hash: {columns_to_hash}")

# Display a sample to verify (first few rows of hashed columns)
print("Contoh data setelah di-hash:")
display(aman[columns_to_hash].head())

Kolom yang di-hash: ['id_peserta', 'nik_dummy', 'no_hp', 'email']
Contoh data setelah di-hash:

     id_peserta     nik_dummy         no_hp         email
0  09b72e9a47af  4246ba5f7a4f  cde3c66576b2  c6d007587f02
1  565439020ae0  45d79dc7aaba  48fea8cd0cd8  273ce0390be4
2  2398346a6926  0bbaedae0a32  1aa102bfa10d  22e490fe98b1
3  97d7aae2281c  ca46fb19a745  78b8fe033bb6  3dc676971085
4  5695b53f5a0a  c6fbe37d0204  e514b43b6471  6ba24926989a

In [29]:
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
TEST_VALUE_A = df.loc[0, 'id_peserta'] # Get a sample value from the original df
hash_a1 = samarkan(TEST_VALUE_A, GARAM)
hash_a2 = samarkan(TEST_VALUE_A, GARAM)
print(f"Nilai asli A: {TEST_VALUE_A}")
print(f"Hash A pertama: {hash_a1}")
print(f"Hash A kedua: {hash_a2}")
print(f"Hasil hash identik: {hash_a1 == hash_a2}\n")

# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda
TEST_VALUE_B1 = df.loc[0, 'email'] # Get another sample value
TEST_VALUE_B2 = df.loc[1, 'email'] # Get a different sample value
hash_b1 = samarkan(TEST_VALUE_B1, GARAM)
hash_b2 = samarkan(TEST_VALUE_B2, GARAM)
print(f"Nilai asli B1: {TEST_VALUE_B1}")
print(f"Nilai asli B2: {TEST_VALUE_B2}")
print(f"Hash B1: {hash_b1}")
print(f"Hash B2: {hash_b2}")
print(f"Hasil hash berbeda: {hash_b1 != hash_b2}")

Nilai asli A: PLT-2025-1309
Hash A pertama: 09b72e9a47af
Hash A kedua: 09b72e9a47af
Hasil hash identik: True

Nilai asli B1: ratna.hidayat@contoh.example
Nilai asli B2: bunga.santoso@contoh.example
Hash B1: c6d007587f02
Hash B2: 273ce0390be4
Hasil hash berbeda: True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

_(tulis di sini)_

In [30]:
ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta pada tanggal acuan 1 September 2025
aman['usia'] = (ACUAN - aman['tanggal_lahir']).dt.days / 365.25

# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
bins = [0, 25, 35, 45, 55, np.inf]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(aman['usia'], bins=bins, labels=labels, right=False)

# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'])

# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
aman['kecamatan'] = aman['kecamatan'].str.title()

print(f"Kelompok umur terbanyak: {aman['kelompok_umur'].value_counts().idxmax()}")
print(f"Jumlah nilai unik di kolom 'kecamatan': {aman['kecamatan'].nunique()}")
display(aman.head())

Kelompok umur terbanyak: 35-44
Jumlah nilai unik di kolom 'kecamatan': 10

,id_peserta,nik_dummy,no_hp,email,kecamatan,kota,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan,usia,kelompok_umur
0,09b72e9a47af,4246ba5f7a4f,cde3c66576b2,c6d007587f02,Tapos,Depok,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0,36.301164,35-44
1,565439020ae0,45d79dc7aaba,48fea8cd0cd8,273ce0390be4,Pancoran Mas,Depok,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9,37.856263,35-44
2,2398346a6926,0bbaedae0a32,1aa102bfa10d,22e490fe98b1,Limo,Depok,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9,27.143053,25-34
3,97d7aae2281c,ca46fb19a745,78b8fe033bb6,3dc676971085,Bojongsari,Depok,L,SMA/SMK,Tidak,2,1250000,Dapur Lestari Jaya,Kuliner,Roti dan kue,12.1,11,6300000,Ya,WhatsApp,2025-05-11,94,50,63.0,5.0,41.806982,35-44
4,5695b53f5a0a,c6fbe37d0204,e514b43b6471,6ba24926989a,Sukmajaya,Depok,P,SMP,Tidak,2,2650000,Studio Sejahtera Abadi,Jasa Digital,Desain grafis,3.2,0,12050000,Tidak,Formulir daring,2025-05-05,89,54,69.0,5.0,52.202601,45-54

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [34]:
def cek_k(data, kolom):
    if not kolom:
        return 0, 0, 0 # No columns to group by

    # Group by the specified columns and count occurrences
    grup_counts = data.groupby(kolom).size()

    # Calculate k (smallest group size)
    k = grup_counts.min() if not grup_counts.empty else 0

    # Calculate number of groups with only one person
    grup_satu_orang = (grup_counts == 1).sum()

    # Calculate total number of groups
    total_grup = len(grup_counts)

    return pd.Series({'k': k, 'grup_satu_orang': grup_satu_orang, 'total_grup': total_grup})

In [35]:
kolom_quasi_sebelum = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
hasil_sebelum = cek_k(df, kolom_quasi_sebelum)

print(f"Risiko sebelum penanganan:")
print(f"  k (ukuran grup terkecil): {hasil_sebelum['k']}")
print(f"  Grup berisi 1 orang: {hasil_sebelum['grup_satu_orang']}")
print(f"  Total grup: {hasil_sebelum['total_grup']}")

# Verification
if hasil_sebelum['k'] == 1 and hasil_sebelum['grup_satu_orang'] == df.shape[0]:
    print("Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang (terbukti).")
else:
    print("Warning: Output does not match expected results.")

Risiko sebelum penanganan:
  k (ukuran grup terkecil): 0
  Grup berisi 1 orang: 620
  Total grup: 186576
Warning: Output does not match expected results.

/tmp/ipykernel_1588/2256799785.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup_counts = data.groupby(kolom).size()

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_(tulis di sini)_

In [36]:
kolom_quasi_sesudah = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
hasil_sesudah = cek_k(aman, kolom_quasi_sesudah)

print(f"Risiko sesudah generalisasi:")
print(f"  k (ukuran grup terkecil): {hasil_sesudah['k']}")
print(f"  Grup berisi 1 orang: {hasil_sesudah['grup_satu_orang']}")
print(f"  Total grup: {hasil_sesudah['total_grup']}")

# Verification
# The exact number for 'grup_satu_orang' is not specified, but it should be significantly lower than df.shape[0]
if hasil_sesudah['k'] == 1 and hasil_sesudah['grup_satu_orang'] < df.shape[0]:
    print("Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1 (terbukti).")
else:
    print("Warning: Output does not match expected results.")

Risiko sesudah generalisasi:
  k (ukuran grup terkecil): 0
  Grup berisi 1 orang: 138
  Total grup: 600
Warning: Output does not match expected results.

/tmp/ipykernel_1588/2256799785.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup_counts = data.groupby(kolom).size()

In [37]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.
# Anda boleh: memperlebar kelompok umur, menggabungkan kecamatan kecil menjadi 'Lainnya',
# atau mengeluarkan satu kolom dari daftar quasi-identifier.
# Catat setiap pilihan dan dampaknya terhadap k.
# Petunjuk: ada lebih dari satu jawaban benar. Yang dinilai adalah alasannya.

# Strategi 1: Menggabungkan kecamatan kecil menjadi 'Lainnya'
# Identifikasi kecamatan dengan frekuensi rendah
kecamatan_counts = aman['kecamatan'].value_counts()
low_frequency_kecamatan = kecamatan_counts[kecamatan_counts < 5].index.tolist()

# Buat salinan DataFrame untuk eksperimen agar aman tidak terpengaruh langsung oleh percobaan
aman_exp = aman.copy()

# Ganti kecamatan dengan frekuensi rendah menjadi 'Lainnya'
aman_exp['kecamatan_grouped'] = aman_exp['kecamatan'].replace(low_frequency_kecamatan, 'Lainnya')

print(f"Original unique kecamatan count: {aman['kecamatan'].nunique()}")
print(f"Grouped unique kecamatan count: {aman_exp['kecamatan_grouped'].nunique()}\n")

# Ukur risiko SESUDAH generalisasi 'kecamatan'
kolom_quasi_final = ['kecamatan_grouped', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
hasil_final = cek_k(aman_exp, kolom_quasi_final)

print(f"Risiko sesudah generalisasi kecamatan (grouped):")
print(f"  k (ukuran grup terkecil): {hasil_final['k']}")
print(f"  Grup berisi 1 orang: {hasil_final['grup_satu_orang']}")
print(f"  Total grup: {hasil_final['total_grup']}")

# Jika k masih di bawah 5, coba strategi lain atau kombinasi
if hasil_final['k'] < 5:
    print("\nK-anonymity (k) is still less than 5 after grouping small kecamatan. Trying further generalization...")
    # Strategi 2: Perlebar kelompok umur (misal, menjadi lebih besar)
    # Hapus kolom 'kelompok_umur' yang lama untuk membuat yang baru
    aman_exp = aman_exp.drop(columns=['kelompok_umur'])

    bins_broad = [0, 30, 40, 50, np.inf] # Contoh kelompok umur yang lebih lebar
    labels_broad = ['<30', '30-39', '40-49', '50+']
    aman_exp['kelompok_umur_broad'] = pd.cut(aman_exp['usia'], bins=bins_broad, labels=labels_broad, right=False)

    kolom_quasi_final_broad = ['kecamatan_grouped', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur_broad']
    hasil_final_broad = cek_k(aman_exp, kolom_quasi_final_broad)

    print(f"\nRisiko sesudah generalisasi kecamatan DAN kelompok umur (broad):")
    print(f"  k (ukuran grup terkecil): {hasil_final_broad['k']}")
    print(f"  Grup berisi 1 orang: {hasil_final_broad['grup_satu_orang']}")
    print(f"  Total grup: {hasil_final_broad['total_grup']}")

    # If k is still not 5, we might need to remove a quasi-identifier or combine categories even further.
    # For this exercise, let's assume one of these steps will be sufficient for k>=5.
    if hasil_final_broad['k'] >= 5:
        aman = aman_exp # Update 'aman' with the successful generalization
        print("\nBerhasil mencapai k >= 5 dengan generalisasi kecamatan dan kelompok umur.")
    else:
        print("\nK-anonymity still not >= 5. Consider removing a quasi-identifier or more aggressive generalization.")
else:
    aman = aman_exp # Update 'aman' with the successful generalization
    print("\nBerhasil mencapai k >= 5 dengan generalisasi kecamatan.")

# Ensure the 'aman' dataframe has the final generalized columns if k>=5 is met
if hasil_final['k'] >= 5: # If the first strategy worked
    aman['kecamatan'] = aman_exp['kecamatan_grouped']
elif 'kelompok_umur_broad' in aman_exp.columns and hasil_final_broad['k'] >= 5: # If the second strategy worked
    aman['kecamatan'] = aman_exp['kecamatan_grouped']
    aman['kelompok_umur'] = aman_exp['kelompok_umur_broad']

# Cleaning up temporary columns for next steps if needed, or if only one strategy worked
if 'kecamatan_grouped' in aman.columns:
    aman = aman.drop(columns=['kecamatan_grouped'])
if 'kelompok_umur_broad' in aman.columns:
    aman = aman.drop(columns=['kelompok_umur_broad'])

Original unique kecamatan count: 10
Grouped unique kecamatan count: 10

Risiko sesudah generalisasi kecamatan (grouped):
  k (ukuran grup terkecil): 0
  Grup berisi 1 orang: 138
  Total grup: 600

K-anonymity (k) is still less than 5 after grouping small kecamatan. Trying further generalization...

Risiko sesudah generalisasi kecamatan DAN kelompok umur (broad):
  k (ukuran grup terkecil): 0
  Grup berisi 1 orang: 112
  Total grup: 480

K-anonymity still not >= 5. Consider removing a quasi-identifier or more aggressive generalization.

/tmp/ipykernel_1588/2256799785.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup_counts = data.groupby(kolom).size()
/tmp/ipykernel_1588/2256799785.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup_counts = data.groupby(kolom).size()

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_(tulis di sini)_

In [38]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
# Expected: ada sel bernilai 1-4; sel seperti ini tidak boleh ditampilkan apa adanya di laporan

In [39]:
cross_tab = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])
display(cross_tab)

# Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
small_cells = (cross_tab >= 1) & (cross_tab < 5)
count_small_cells = small_cells.sum().sum()

print(f"\nJumlah sel yang berisi 1-4 peserta: {count_small_cells}")

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel yang berisi 1-4 peserta: 9

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

_(tulis di sini)_

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber | |
| Tautan atau nama instansi | |
| Tanggal pengambilan | |
| Lisensi atau nomor surat izin | |
| Kalimat sitasi untuk laporan | |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [27]:
# G4 — jalankan penanganan pada data tim dan periksa nilai k
# Salin pola Bagian E dan F, ganti dataset dan nama kolomnya.
# Simpan hasilnya ke data/processed/ dan JANGAN unggah data/raw/

### G4 — Jalankan Penanganan pada Data Tim dan Periksa Nilai k

Untuk bagian ini, Anda akan menerapkan langkah-langkah yang sama seperti di Bagian E (penanganan data) dan Bagian F (pemeriksaan risiko k-anonimitas) pada dataset tim Anda sendiri.

**Langkah-langkah yang perlu Anda lakukan:**
1.  **Muat dataset tim Anda.** Pastikan file dataset berada di lokasi yang dapat diakses (misalnya, di folder yang sama dengan notebook ini, atau melalui Google Drive jika Anda mount).
2.  **Definisikan `PENANDAAN_TEAM`** sesuai dengan kolom-kolom di dataset tim Anda. Ini adalah dictionary yang memetakan nama kolom ke kategori privasi dan tindakan penanganan yang Anda pilih (misalnya, 'hapus', 'hash', 'generalisasi', 'pertahankan').
3.  **Sesuaikan nama kolom** di setiap blok kode dengan nama kolom yang relevan di dataset tim Anda (misalnya, `tanggal_lahir`, `kecamatan`, `kelurahan`, `usia`, `kelompok_umur`).
4.  **Periksa dan catat nilai k** yang dicapai setelah setiap langkah generalisasi.

In [41]:
# 1. Muat Dataset Tim Anda
# Ganti 'nama_file_dataset_tim_anda.csv' dengan nama file CSV dataset tim Anda
# dan sesuaikan pemisah (delimiter) jika bukan koma.
TEAM_FILE = 'nama_file_dataset_tim_anda.csv' # Ganti dengan nama file dataset Anda

# Pastikan Anda telah mengunggah file atau mount Google Drive jika file ada di Drive
# Contoh: df_team = pd.read_csv(TEAM_FILE)
# Untuk contoh ini, saya akan menggunakan df yang sudah ada sebagai placeholder
# HAPUS BARIS INI DAN AKTIFKAN BARIS DI ATAS setelah Anda mengatur dataset tim Anda
df_team = df.copy()

print(f"Dataset tim Anda dimuat dengan {df_team.shape[0]} baris dan {df_team.shape[1]} kolom.")

# 2. Definisikan PENANDAAN_TEAM untuk dataset Anda
# Sesuaikan kategori dan tindakan untuk setiap kolom di dataset tim Anda.
# Ini adalah contoh, Anda harus mengisi sesuai dengan kolom dataset Anda.
PENANDAAN_TEAM = {
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hash'),
    'no_hp': ('pengenal langsung', 'hash'),
    'email': ('pengenal langsung', 'hash'),
    'alamat_jalan': ('quasi-identifier', 'hapus'),
    'kelurahan': ('quasi-identifier', 'generalisasi'), # Ganti dengan kolom kelurahan Anda
    'kecamatan': ('quasi-identifier', 'generalisasi'), # Ganti dengan kolom kecamatan Anda
    'tanggal_lahir': ('data spesifik', 'generalisasi'), # Ganti dengan kolom tanggal lahir Anda
    'status_disabilitas': ('data spesifik', 'pertahankan'),
    'jumlah_anak': ('data spesifik', 'pertahankan'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'pertahankan'),
    'omzet_usaha_bulanan': ('data spesifik', 'pertahankan'),
    'nama_usaha': ('quasi-identifier', 'pertahankan')
    # Tambahkan kolom lain dari dataset tim Anda di sini
}

# Buat DataFrame 'tanda_team'
tanda_team_list = []
for col in df_team.columns:
    kategori, tindakan = PENANDAAN_TEAM.get(col, ('bukan data pribadi', 'pertahankan'))
    tanda_team_list.append({
        'nama_kolom': col,
        'kategori': kategori,
        'tindakan': tindakan
    })

tanda_team = pd.DataFrame(tanda_team_list)

print("\nJumlah kolom per kategori (dataset tim):")
print(tanda_team['kategori'].value_counts())
display(tanda_team.head())

# Buat salinan DataFrame untuk penanganan
aman_team = df_team.copy()

Dataset tim Anda dimuat dengan 620 baris dan 28 kolom.

Jumlah kolom per kategori (dataset tim):
kategori
bukan data pribadi    14
pengenal langsung      5
data spesifik          5
quasi-identifier       4
Name: count, dtype: int64

     nama_kolom           kategori tindakan
0    id_peserta  pengenal langsung     hash
1  nama_lengkap  pengenal langsung    hapus
2     nik_dummy  pengenal langsung     hash
3         no_hp  pengenal langsung     hash
4         email  pengenal langsung     hash

In [42]:
# 3. Menerapkan Tindakan 'Hapus' (Dropping Columns)
columns_to_drop_team = tanda_team[tanda_team['tindakan'] == 'hapus']['nama_kolom'].tolist()

aman_team = aman_team.drop(columns=columns_to_drop_team, errors='ignore')

print(f"Jumlah kolom yang dibuang dari aman_team: {len(columns_to_drop_team)}")
print(f"Jumlah kolom yang tersisa di aman_team: {aman_team.shape[1]}")

# 4. Menerapkan Tindakan 'Hash' (Hashing Columns)
# Gunakan GARAM yang berbeda untuk dataset tim Anda!
GARAM_TEAM = 'garam-rahasia-tim-anda' # GANTI DENGAN KALIMAT RAHASIA YANG UNIK UNTUK TIM ANDA

# Pastikan fungsi `samarkan` sudah didefinisikan di sel sebelumnya (zBZE1cOr-x55)

columns_to_hash_team = tanda_team[tanda_team['tindakan'] == 'hash']['nama_kolom'].tolist()

for col in columns_to_hash_team:
    if col in aman_team.columns: # Pastikan kolom masih ada setelah penghapusan
        aman_team[col] = aman_team[col].apply(lambda x: samarkan(x, GARAM_TEAM))
    else:
        print(f"Kolom '{col}' tidak ditemukan di aman_team (mungkin sudah dihapus).")

print(f"\nKolom yang di-hash di aman_team: {columns_to_hash_team}")

# Display a sample to verify (first few rows of hashed columns)
print("Contoh data setelah di-hash (aman_team):")
display(aman_team[columns_to_hash_team].head())

Jumlah kolom yang dibuang dari aman_team: 2
Jumlah kolom yang tersisa di aman_team: 26

Kolom yang di-hash di aman_team: ['id_peserta', 'nik_dummy', 'no_hp', 'email']
Contoh data setelah di-hash (aman_team):

     id_peserta     nik_dummy         no_hp         email
0  a270594e13b1  388eadebeefe  a3664ab8029a  e6e1c3668a7c
1  30e284ecfa1f  5a41661f9abb  96003ea9173e  4d12df132f6a
2  2ac7ea4cd7b2  61f4c0c96809  c62ed08b1c3a  9cc7abcbd5b6
3  8d9bc3fb6bf8  6cc807a93c86  855b8a5ec221  06c2bd23a222
4  9afa9505b790  9c924c755fa3  5c85639be09c  fe4951dd9d13

In [43]:
# 5. Menerapkan Tindakan 'Generalisasi' (Age Grouping dan Kecamatan Cleaning)

# Sesuaikan nama kolom jika berbeda di dataset tim Anda
COLUMN_TANGGAL_LAHIR_TEAM = 'tanggal_lahir' # Ganti dengan nama kolom tanggal lahir Anda
COLUMN_KELURAHAN_TEAM = 'kelurahan'       # Ganti dengan nama kolom kelurahan Anda
COLUMN_KECAMATAN_TEAM = 'kecamatan'       # Ganti dengan nama kolom kecamatan Anda

# Konversi kolom tanggal lahir ke datetime jika belum
if COLUMN_TANGGAL_LAHIR_TEAM in aman_team.columns:
    aman_team[COLUMN_TANGGAL_LAHIR_TEAM] = pd.to_datetime(aman_team[COLUMN_TANGGAL_LAHIR_TEAM], errors='coerce')

    # Tentukan tanggal acuan untuk perhitungan usia (sesuaikan jika perlu)
    ACUAN_TEAM = pd.Timestamp('2025-09-01') # Sesuaikan tanggal acuan untuk dataset Anda

    # a. Hitung usia peserta
    aman_team['usia'] = (ACUAN_TEAM - aman_team[COLUMN_TANGGAL_LAHIR_TEAM]).dt.days / 365.25

    # b. Buat kolom 'kelompok_umur' (sesuaikan bin dan label jika diperlukan)
    bins_umur_team = [0, 25, 35, 45, 55, np.inf]
    labels_umur_team = ['<25', '25-34', '35-44', '45-54', '55+']
    aman_team['kelompok_umur'] = pd.cut(aman_team['usia'], bins=bins_umur_team, labels=labels_umur_team, right=False)

    print(f"Kelompok umur terbanyak di aman_team: {aman_team['kelompok_umur'].value_counts().idxmax()}")
else:
    print(f"Kolom '{COLUMN_TANGGAL_LAHIR_TEAM}' tidak ditemukan di aman_team. Usia dan kelompok umur tidak dihitung.")

# c. Buang kolom asli yang digeneralisasi ('tanggal_lahir' dan 'kelurahan')
col_to_drop_after_gen = []
if COLUMN_TANGGAL_LAHIR_TEAM in aman_team.columns:
    col_to_drop_after_gen.append(COLUMN_TANGGAL_LAHIR_TEAM)
if COLUMN_KELURAHAN_TEAM in aman_team.columns:
    col_to_drop_after_gen.append(COLUMN_KELURAHAN_TEAM)

aman_team = aman_team.drop(columns=col_to_drop_after_gen, errors='ignore')

# d. Rapikan kolom kecamatan (jika ada)
if COLUMN_KECAMATAN_TEAM in aman_team.columns:
    aman_team[COLUMN_KECAMATAN_TEAM] = aman_team[COLUMN_KECAMATAN_TEAM].str.title()
    print(f"Jumlah nilai unik di kolom '{COLUMN_KECAMATAN_TEAM}' aman_team: {aman_team[COLUMN_KECAMATAN_TEAM].nunique()}")
else:
    print(f"Kolom '{COLUMN_KECAMATAN_TEAM}' tidak ditemukan di aman_team.")

display(aman_team.head())

Kelompok umur terbanyak di aman_team: 35-44
Jumlah nilai unik di kolom 'kecamatan' aman_team: 10

,id_peserta,nik_dummy,no_hp,email,kecamatan,kota,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan,usia,kelompok_umur
0,a270594e13b1,388eadebeefe,a3664ab8029a,e6e1c3668a7c,Tapos,Depok,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0,36.301164,35-44
1,30e284ecfa1f,5a41661f9abb,96003ea9173e,4d12df132f6a,Pancoran Mas,Depok,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9,37.856263,35-44
2,2ac7ea4cd7b2,61f4c0c96809,c62ed08b1c3a,9cc7abcbd5b6,Limo,Depok,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9,27.143053,25-34
3,8d9bc3fb6bf8,6cc807a93c86,855b8a5ec221,06c2bd23a222,Bojongsari,Depok,L,SMA/SMK,Tidak,2,1250000,Dapur Lestari Jaya,Kuliner,Roti dan kue,12.1,11,6300000,Ya,WhatsApp,2025-05-11,94,50,63.0,5.0,41.806982,35-44
4,9afa9505b790,9c924c755fa3,5c85639be09c,fe4951dd9d13,Sukmajaya,Depok,P,SMP,Tidak,2,2650000,Studio Sejahtera Abadi,Jasa Digital,Desain grafis,3.2,0,12050000,Tidak,Formulir daring,2025-05-05,89,54,69.0,5.0,52.202601,45-54

In [44]:
# 6. Periksa K-Anonymity pada aman_team
# Pastikan fungsi `cek_k` sudah didefinisikan di sel sebelumnya (zBZE1cOr-x55)

# --- Pastikan variabel nama kolom ini didefinisikan ulang untuk menghindari NameError ---
COLUMN_TANGGAL_LAHIR_TEAM = 'tanggal_lahir' # Ganti dengan nama kolom tanggal lahir Anda
COLUMN_KELURAHAN_TEAM = 'kelurahan'       # Ganti dengan nama kolom kelurahan Anda
COLUMN_KECAMATAN_TEAM = 'kecamatan'       # Ganti dengan nama kolom kecamatan Anda
# --------------------------------------------------------------------------------------

# Definisikan daftar quasi-identifier untuk dataset tim Anda
# Sesuaikan dengan kolom yang relevan setelah penanganan
kolom_quasi_team = [
    COLUMN_KECAMATAN_TEAM, # Sesuaikan nama kolom kecamatan
    'jenis_kelamin', # Sesuaikan nama kolom jenis kelamin
    'pendidikan_terakhir', # Sesuaikan nama kolom pendidikan terakhir
    'kelompok_umur' # Sesuaikan nama kolom kelompok umur yang baru dibuat
]

hasil_team = cek_k(aman_team, kolom_quasi_team)

print(f"Risiko k-anonimitas untuk dataset tim setelah generalisasi awal:")
print(f"  k (ukuran grup terkecil): {hasil_team['k']}")
print(f"  Grup berisi 1 orang: {hasil_team['grup_satu_orang']}")
print(f"  Total grup: {hasil_team['total_grup']}")

# Jika k masih kurang dari 5, Anda perlu menerapkan generalisasi lebih lanjut secara manual.
# Contoh strategi:
# 1. Menggabungkan kategori 'kecamatan' dengan frekuensi rendah menjadi 'Lainnya'.
# 2. Memperlebar rentang 'kelompok_umur' (misalnya, [<30, 30-49, 50+]).
# 3. Mengeluarkan satu kolom dari daftar quasi-identifier (namun ini mengurangi informasi).

Risiko k-anonimitas untuk dataset tim setelah generalisasi awal:
  k (ukuran grup terkecil): 0
  Grup berisi 1 orang: 138
  Total grup: 600

/tmp/ipykernel_1588/2256799785.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup_counts = data.groupby(kolom).size()

### Tips untuk Mencapai k >= 5 (jika diperlukan):

Jika `k` masih di bawah 5, Anda dapat mengulang langkah generalisasi dengan strategi yang lebih agresif. Contohnya:

*   **Mengelompokkan `kecamatan` yang jarang:**

    ```python
    # Identifikasi kecamatan dengan frekuensi rendah
    kecamatan_counts_team = aman_team[COLUMN_KECAMATAN_TEAM].value_counts()
    low_frequency_kecamatan_team = kecamatan_counts_team[kecamatan_counts_team < 5].index.tolist()

    aman_team['kecamatan_grouped'] = aman_team[COLUMN_KECAMATAN_TEAM].replace(low_frequency_kecamatan_team, 'Lainnya')
    # Kemudian, gunakan 'kecamatan_grouped' di `kolom_quasi_team` Anda
    # Jangan lupa untuk memperbarui `aman_team[COLUMN_KECAMATAN_TEAM] = aman_team['kecamatan_grouped']` dan menghapus `kecamatan_grouped`
    ```

*   **Memperlebar kelompok umur:**

    ```python
    # Hapus kolom 'kelompok_umur' yang lama jika Anda membuat yang baru
    # aman_team = aman_team.drop(columns=['kelompok_umur'])
    
    bins_broad_team = [0, 30, 50, np.inf] # Contoh kelompok umur yang lebih lebar
    labels_broad_team = ['<30', '30-49', '50+']
    aman_team['kelompok_umur_broad'] = pd.cut(aman_team['usia'], bins=bins_broad_team, labels=labels_broad_team, right=False)
    # Kemudian, gunakan 'kelompok_umur_broad' di `kolom_quasi_team` Anda
    # Jangan lupa untuk memperbarui `aman_team['kelompok_umur'] = aman_team['kelompok_umur_broad']` dan menghapus `kelompok_umur_broad`
    ```

Setelah menerapkan generalisasi tambahan, jalankan ulang pemeriksaan `cek_k` untuk melihat dampaknya.

In [45]:
# Simpan DataFrame aman_team ke data/processed/
import os

output_dir = 'data/processed'
os.makedirs(output_dir, exist_ok=True)

output_file = os.path.join(output_dir, 'aman_team_processed.csv')

aman_team.to_csv(output_file, index=False)

print(f"DataFrame 'aman_team' telah disimpan ke: {output_file}")

DataFrame 'aman_team' telah disimpan ke: data/processed/aman_team_processed.csv

### G5 — Daftar periksa sebelum `git push`

- [ ] `data/raw/` masuk `.gitignore`
- [ ] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ ] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ ] Garam hash tidak tertulis di dalam notebook
- [ ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ ] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ ] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.